//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CURDUSERMGMT.Models
  
{
    using System;
    using System.Collections.Generic;    
    using System.ComponentModel.DataAnnotations;

    public partial class t_user_profile
    {
        [Required]
        public string t_user_Id { get; set; }
        public string t_user_FirstName { get; set; }
        public string t_user_LastName { get; set; }
        [EmailAddress]
        public string t_user_Email { get; set; }
        //[Required]
        public string t_user_Pass { get; set; }
        public string t_user_Status { get; set; }
        public Nullable<System.DateTime> t_user_UpdateDt { get; set; }
        public string t_user_UpdateBy { get; set; }
        public Nullable<System.DateTime> t_user_LoginTime { get; set; }
        public Nullable<System.DateTime> t_user_LogoutTime { get; set; }
    }
}
